"""fix field token

Revision ID: 7b204d9cccf1
Revises: 20e0fd8d02b0
Create Date: 2023-02-01 15:50:41.671180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b204d9cccf1'
down_revision = '20e0fd8d02b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', sa.String(length=255), nullable=True))
    op.alter_column('users', 'avatar',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'refresh_token')
    # ### end Alembic commands ###
